### ISSUE TITLE
ConfigGroup elements should be collapsable

### ISSUE THREAD

**Issue by PrinceNebulon** [T-Boss/WpfConfigurator#6]
Add a collapse/expand control to each config group UI element so they can be collapsed.

**Comment by T-Boss** [comment]
Also allow for config groups to be collapsed by default

**Comment by PrinceNebulon** [comment]
done https://github.com/T-Boss/WpfConfigurator/commit/1f69daf7cf3bce1870624bca8fc05dc641cd85c8
